#!/usr/bin/env python3
"""Re-derive character_drops.json from THIS repo's own roster data.

The rule (user, 2026-07-25): a character with fewer than six fully-evolved
Pokemon obtainable in this game is not offered here -- unless a legendary or
mythical is on the roster, which exempts them. They keep their table slot and
are hidden from the selection menu, because saves store the character INDEX and
deleting a row would repoint every existing save at a different character.
(That is not hypothetical here: the 2026-07-25 audit emptied four rosters that
had already shipped, Viola at index 117 among them.)

Why this script exists: the drop list was originally computed by the audit's
`per_game_threshold.py`, which reads the audit's own `final_rosters.json`. That
file does not include this repo's `roster_additions.json` overlay, wave 5, or
-- and this matters more here than anywhere else -- Stage B's curated-dex
filter, which leaves only 206 of 504 distinct roster species standing. Its
answer drifts from what the ROM actually enforces in BOTH directions.

So: expand each roster with `emit_bitmaps.expand_roster` (the very function that
builds the injected allow-bitmaps, over the very roster ordering
`emit_characters.build_rosters` emits) and count finals with
`emit_roster_docs.FinalIndex` (the very walk that writes the doc rows). Sharing
all three means the threshold, the bitmaps and the docs cannot disagree.

The legendary exemption uses `emit_characters.LEGENDARY_BASES` -- the same set
the emitter uses to split starters from legendaries -- rather than a separate
name list, so "has a legendary" means exactly what the rest of the pipeline
means by it.

Run BEFORE emit_characters.py --final; it rewrites character_drops.json in place.
"""
import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import emit_bitmaps                     # noqa: E402
import emit_characters                  # noqa: E402
import emit_roster_docs                 # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true",
                    help="report only; do not rewrite character_drops.json")
    args = ap.parse_args()

    with open(os.path.join(HERE, "rosters_mapped.json")) as f:
        mapped = json.load(f)
    with open(os.path.join(HERE, "rom_species_table.json")) as f:
        rom_names = {int(k): v for k, v in json.load(f)["species"].items()}

    order = emit_characters.load_order(mapped)
    built, _empty, _warnings = emit_characters.build_rosters(mapped, order)
    const_to_id = emit_characters.const_id_map(mapped)
    tbl = emit_bitmaps.load_expansion_tables()
    index = emit_roster_docs.FinalIndex()

    dropped, kept, exempt = [], [], []
    for disp in order:
        name = emit_characters.display_name(disp)
        consts = built[disp]["ordered_consts"]
        if any(c in emit_characters.LEGENDARY_BASES for c in consts):
            exempt.append(name)
            kept.append(name)
            continue
        allowed = emit_bitmaps.expand_roster([const_to_id[c] for c in consts], tbl)
        finals = index.finals_for_names(rom_names[i] for i in allowed
                                        if i in rom_names)
        if len(finals) < 6:
            dropped.append((name, len(finals)))
        else:
            kept.append(name)

    path = os.path.join(HERE, "character_drops.json")
    old = set()
    if os.path.isfile(path):
        with open(path) as f:
            old = set(json.load(f).get("unselectable", []))
    new = sorted(n for n, _ in dropped)

    if not args.dry_run:
        with open(path, "w", encoding="utf-8") as f:
            json.dump({"_comment": "Characters that stay in the table (saves "
                                   "store the INDEX) but fall under the "
                                   "six-fully-evolved threshold in this game's "
                                   "curated dex, with no legendary to exempt "
                                   "them. GENERATED by derive_drops.py -- do "
                                   "not hand-edit.",
                       "unselectable": new}, f, indent=1, sort_keys=True,
                      ensure_ascii=False)
            f.write("\n")

    print("%d characters: %d clear the threshold (%d of them by legendary "
          "exemption), %d fall under it"
          % (len(order), len(kept), len(exempt), len(new)))
    for n, c in sorted(dropped, key=lambda x: (x[1], x[0])):
        print("   %-18s %d final%s" % (n, c, "" if c == 1 else "s"))
    for n in sorted(set(new) - old):
        print("   + newly under threshold: %s" % n)
    for n in sorted(old - set(new)):
        print("   - now clears threshold:  %s" % n)
    if args.dry_run:
        print("(dry run -- character_drops.json not rewritten)")


if __name__ == "__main__":
    main()
